use_frameworks!
project 'JeniusPNPOC.xcodeproj'

target 'JeniusPNPOC' do
platform :ios, '10.3'
  # Required for Urban Airship
  pod 'UrbanAirship-iOS-SDK'
end

target 'ServiceExtension' do
platform :ios, '10.3'
  # Pods for Service Extension
  pod 'UrbanAirship-iOS-AppExtensions'
end

